# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vagrant_plugin_sdk/plugin.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/struct_pb'
require 'google/rpc/status_pb'
require 'protostructure_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vagrant_plugin_sdk/plugin.proto", :syntax => :proto3) do
    add_message "hashicorp.vagrant.sdk.Args" do
    end
    add_message "hashicorp.vagrant.sdk.Args.DataDir" do
    end
    add_message "hashicorp.vagrant.sdk.Args.DataDir.Basis" do
      optional :cache_dir, :string, 1
      optional :data_dir, :string, 2
      optional :root_dir, :string, 3
      optional :temp_dir, :string, 4
    end
    add_message "hashicorp.vagrant.sdk.Args.DataDir.Project" do
      optional :cache_dir, :string, 1
      optional :data_dir, :string, 2
      optional :root_dir, :string, 3
      optional :temp_dir, :string, 4
    end
    add_message "hashicorp.vagrant.sdk.Args.DataDir.Machine" do
      optional :cache_dir, :string, 1
      optional :data_dir, :string, 2
      optional :root_dir, :string, 3
      optional :temp_dir, :string, 4
    end
    add_message "hashicorp.vagrant.sdk.Args.DataDir.Component" do
      optional :cache_dir, :string, 1
      optional :data_dir, :string, 2
      optional :root_dir, :string, 3
      optional :temp_dir, :string, 4
    end
    add_message "hashicorp.vagrant.sdk.Args.MachineIndex" do
    end
    add_message "hashicorp.vagrant.sdk.Args.MachineIndex.Entry" do
      optional :id, :string, 1
      optional :local_data_path, :string, 2
      optional :name, :string, 3
      optional :provider, :string, 4
      optional :state, :string, 5
      optional :vagrantfile_name, :string, 6
      optional :vagrantfile_path, :string, 7
      optional :updated_at, :string, 8
      optional :extra_data, :message, 9, "hashicorp.vagrant.sdk.Args.Options"
    end
    add_message "hashicorp.vagrant.sdk.Args.BoxCollection" do
      optional :directory, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Args.Box" do
      optional :name, :string, 1
      optional :provider, :string, 2
      optional :version, :string, 3
      optional :directory, :string, 4
      map :metadata, :string, :string, 5
      optional :metadata_url, :string, 6
    end
    add_message "hashicorp.vagrant.sdk.Args.Project" do
      optional :cwd, :string, 1
      optional :data_dir, :string, 2
      optional :vagrantfile_name, :string, 3
      optional :ui, :message, 4, "hashicorp.vagrant.sdk.Args.TerminalUI"
      optional :home_path, :string, 5
      optional :local_data_path, :string, 6
      optional :tmp_path, :string, 7
      optional :aliases_path, :string, 8
      optional :boxes_path, :string, 9
      optional :gems_path, :string, 10
      optional :default_private_key_path, :string, 11
      optional :server_addr, :string, 12
    end
    add_message "hashicorp.vagrant.sdk.Args.Machine" do
      optional :resource_id, :string, 1
      optional :server_addr, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Args.Configuration" do
    end
    add_message "hashicorp.vagrant.sdk.Args.Configuration.Vagrant" do
    end
    add_message "hashicorp.vagrant.sdk.Args.Configuration.VM" do
    end
    add_message "hashicorp.vagrant.sdk.Args.Configuration.Provider" do
    end
    add_message "hashicorp.vagrant.sdk.Args.LabelSet" do
      map :labels, :string, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Args.Options" do
      optional :opt, :message, 1, "hashicorp.vagrant.sdk.Args.LabelSet"
    end
    add_message "hashicorp.vagrant.sdk.Args.Vagrantfile" do
    end
    add_message "hashicorp.vagrant.sdk.Args.JobInfo" do
      optional :local, :bool, 1
      optional :workspace, :string, 2
      optional :id, :string, 3
    end
    add_message "hashicorp.vagrant.sdk.Args.Logger" do
      optional :name, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Args.TerminalUI" do
      optional :stream_id, :uint32, 1
    end
    add_message "hashicorp.vagrant.sdk.Args.StateBag" do
      map :data, :string, :message, 1, "hashicorp.vagrant.sdk.Args.StateBag.Value"
    end
    add_message "hashicorp.vagrant.sdk.Args.StateBag.Value" do
      oneof :value do
        optional :text, :string, 1
        optional :map, :message, 2, "google.protobuf.Any"
      end
    end
    add_message "hashicorp.vagrant.sdk.Args.MachineState" do
      optional :id, :string, 1
      optional :short_description, :string, 2
      optional :long_description, :string, 3
    end
    add_message "hashicorp.vagrant.sdk.Args.SSHInfo" do
      optional :host, :string, 1
      optional :port, :string, 2
      optional :private_key_path, :string, 3
      optional :keys_only, :bool, 4
      optional :verify_host_key, :bool, 5
      optional :username, :string, 6
      optional :remote_user, :string, 7
      optional :compression, :bool, 8
      optional :dsa_authentication, :bool, 9
      optional :config, :string, 10
      repeated :extra_args, :string, 11
      optional :forward_agent, :bool, 12
      optional :forward_x11, :bool, 13
      repeated :forward_env, :string, 14
      optional :connect_timeout, :int64, 15
      optional :ssh_command, :string, 16
      optional :proxy_command, :string, 17
    end
    add_message "hashicorp.vagrant.sdk.Args.WinrmInfo" do
      optional :username, :string, 1
      optional :password, :string, 2
      optional :host, :string, 3
      optional :port, :int64, 4
      optional :guest_port, :int64, 5
      optional :max_tries, :int64, 6
      optional :retry_delay, :int64, 7
      optional :timeout, :int64, 8
      optional :transport, :enum, 9, "hashicorp.vagrant.sdk.Args.WinrmInfo.Transport"
      optional :ssl_peer_verification, :bool, 10
      optional :execution_time_limit, :string, 11
      optional :basic_auth_only, :bool, 12
      optional :codepage, :string, 13
    end
    add_enum "hashicorp.vagrant.sdk.Args.WinrmInfo.Transport" do
      value :NEGOTIATE, 0
      value :SSL, 1
      value :PLAINTEXT, 2
    end
    add_message "hashicorp.vagrant.sdk.FuncSpec" do
      optional :name, :string, 1
      repeated :args, :message, 2, "hashicorp.vagrant.sdk.FuncSpec.Value"
      repeated :result, :message, 3, "hashicorp.vagrant.sdk.FuncSpec.Value"
    end
    add_message "hashicorp.vagrant.sdk.FuncSpec.Value" do
      optional :name, :string, 1
      optional :type, :string, 2
      optional :value, :message, 3, "google.protobuf.Any"
    end
    add_message "hashicorp.vagrant.sdk.FuncSpec.Args" do
      repeated :args, :message, 1, "hashicorp.vagrant.sdk.FuncSpec.Value"
    end
    add_message "hashicorp.vagrant.sdk.Config" do
    end
    add_message "hashicorp.vagrant.sdk.Config.ConfigureRequest" do
      optional :json, :bytes, 1
    end
    add_message "hashicorp.vagrant.sdk.Config.StructResp" do
      optional :struct, :message, 1, "protostructure.Struct"
    end
    add_message "hashicorp.vagrant.sdk.Config.FieldDocumentation" do
      optional :name, :string, 1
      optional :synopsis, :string, 2
      optional :summary, :string, 3
      optional :optional, :bool, 4
      optional :env_var, :string, 5
      optional :type, :string, 6
      optional :default, :string, 7
    end
    add_message "hashicorp.vagrant.sdk.Config.MapperDocumentation" do
      optional :input, :string, 1
      optional :output, :string, 2
      optional :description, :string, 3
    end
    add_message "hashicorp.vagrant.sdk.Config.Documentation" do
      optional :description, :string, 1
      optional :example, :string, 2
      optional :input, :string, 3
      optional :output, :string, 4
      map :fields, :string, :message, 5, "hashicorp.vagrant.sdk.Config.FieldDocumentation"
      repeated :mappers, :message, 6, "hashicorp.vagrant.sdk.Config.MapperDocumentation"
    end
    add_message "hashicorp.vagrant.sdk.Auth" do
    end
    add_message "hashicorp.vagrant.sdk.Auth.AuthResponse" do
      optional :authenticated, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.ImplementsResp" do
      optional :implements, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI" do
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.IsInteractiveResponse" do
      optional :interactive, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.OutputRequest" do
      repeated :lines, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Response" do
      oneof :event do
        optional :input, :message, 1, "hashicorp.vagrant.sdk.TerminalUI.Event.InputResp"
      end
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event" do
      oneof :event do
        optional :line, :message, 1, "hashicorp.vagrant.sdk.TerminalUI.Event.Line"
        optional :status, :message, 2, "hashicorp.vagrant.sdk.TerminalUI.Event.Status"
        optional :named_values, :message, 3, "hashicorp.vagrant.sdk.TerminalUI.Event.NamedValues"
        optional :raw, :message, 4, "hashicorp.vagrant.sdk.TerminalUI.Event.Raw"
        optional :table, :message, 5, "hashicorp.vagrant.sdk.TerminalUI.Event.Table"
        optional :step_group, :message, 6, "hashicorp.vagrant.sdk.TerminalUI.Event.StepGroup"
        optional :step, :message, 7, "hashicorp.vagrant.sdk.TerminalUI.Event.Step"
        optional :input, :message, 8, "hashicorp.vagrant.sdk.TerminalUI.Event.Input"
      end
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.Input" do
      optional :prompt, :string, 1
      optional :style, :string, 2
      optional :secret, :bool, 3
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.InputResp" do
      optional :input, :string, 1
      optional :error, :message, 2, "google.rpc.Status"
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.Status" do
      optional :status, :string, 1
      optional :msg, :string, 2
      optional :step, :bool, 3
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.Line" do
      optional :msg, :string, 1
      optional :style, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.Raw" do
      optional :data, :bytes, 1
      optional :stderr, :bool, 2
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.NamedValue" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.NamedValues" do
      repeated :values, :message, 1, "hashicorp.vagrant.sdk.TerminalUI.Event.NamedValue"
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.TableEntry" do
      optional :value, :string, 1
      optional :color, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.TableRow" do
      repeated :entries, :message, 1, "hashicorp.vagrant.sdk.TerminalUI.Event.TableEntry"
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.Table" do
      repeated :headers, :string, 1
      repeated :rows, :message, 2, "hashicorp.vagrant.sdk.TerminalUI.Event.TableRow"
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.StepGroup" do
      optional :close, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.TerminalUI.Event.Step" do
      optional :id, :int32, 1
      optional :close, :bool, 2
      optional :msg, :string, 3
      optional :status, :string, 4
      optional :output, :bytes, 5
    end
    add_message "hashicorp.vagrant.sdk.Map" do
    end
    add_message "hashicorp.vagrant.sdk.Map.Request" do
      optional :args, :message, 1, "hashicorp.vagrant.sdk.FuncSpec.Args"
      optional :result, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Map.Response" do
      optional :result, :message, 1, "google.protobuf.Any"
    end
    add_message "hashicorp.vagrant.sdk.Map.ListResponse" do
      repeated :funcs, :message, 1, "hashicorp.vagrant.sdk.FuncSpec"
    end
    add_message "hashicorp.vagrant.sdk.Provider" do
    end
    add_message "hashicorp.vagrant.sdk.Provider.UsableResp" do
      optional :is_usable, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Provider.InstalledResp" do
      optional :is_installed, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Provider.ActionResp" do
      optional :result, :message, 1, "google.protobuf.Any"
      map :labels, :string, :string, 2
      optional :template_data, :bytes, 3
      optional :success, :bool, 4
    end
    add_message "hashicorp.vagrant.sdk.Command" do
    end
    add_message "hashicorp.vagrant.sdk.Command.Flag" do
      optional :long_name, :string, 1
      optional :short_name, :string, 2
      optional :description, :string, 3
      optional :default_value, :string, 4
      optional :type, :enum, 5, "hashicorp.vagrant.sdk.Command.Flag.Type"
    end
    add_enum "hashicorp.vagrant.sdk.Command.Flag.Type" do
      value :STRING, 0
      value :BOOL, 2
    end
    add_message "hashicorp.vagrant.sdk.Command.CommandInfo" do
      optional :name, :string, 1
      optional :help, :string, 2
      optional :synopsis, :string, 3
      repeated :flags, :message, 4, "hashicorp.vagrant.sdk.Command.Flag"
      repeated :subcommands, :message, 5, "hashicorp.vagrant.sdk.Command.CommandInfo"
    end
    add_message "hashicorp.vagrant.sdk.Command.CommandInfoResp" do
      optional :command_info, :message, 1, "hashicorp.vagrant.sdk.Command.CommandInfo"
    end
    add_message "hashicorp.vagrant.sdk.Command.ExecuteResp" do
      optional :exit_code, :int64, 1
    end
    add_message "hashicorp.vagrant.sdk.Command.ExecuteReq" do
      optional :spec, :message, 1, "hashicorp.vagrant.sdk.FuncSpec.Args"
      repeated :command_args, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Command.ExecuteSpecReq" do
      repeated :command_args, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Command.Arguments" do
      repeated :flags, :message, 1, "hashicorp.vagrant.sdk.Command.Arguments.Flag"
      repeated :args, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Command.Arguments.Flag" do
      optional :name, :string, 1
      optional :type, :enum, 4, "hashicorp.vagrant.sdk.Command.Arguments.Flag.Type"
      oneof :value do
        optional :string, :string, 2
        optional :bool, :bool, 3
      end
    end
    add_enum "hashicorp.vagrant.sdk.Command.Arguments.Flag.Type" do
      value :STRING, 0
      value :BOOL, 1
    end
    add_message "hashicorp.vagrant.sdk.Communicator" do
    end
    add_message "hashicorp.vagrant.sdk.Communicator.MatchResp" do
      optional :match, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Communicator.InitResp" do
    end
    add_message "hashicorp.vagrant.sdk.Communicator.ReadyResp" do
      optional :ready, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Communicator.FileTransferResp" do
    end
    add_message "hashicorp.vagrant.sdk.Communicator.ExecutionRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Args.Machine"
      optional :command, :string, 2
      optional :options, :message, 3, "hashicorp.vagrant.sdk.Args.LabelSet"
    end
    add_message "hashicorp.vagrant.sdk.Communicator.ExecuteResp" do
      optional :exit_code, :int32, 1
    end
    add_message "hashicorp.vagrant.sdk.Communicator.TestResp" do
      optional :valid, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Communicator.ResetResp" do
    end
    add_message "hashicorp.vagrant.sdk.Guest" do
    end
    add_message "hashicorp.vagrant.sdk.Guest.DetectResp" do
      optional :detected, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Guest.Capability" do
    end
    add_message "hashicorp.vagrant.sdk.Guest.Capability.NamedRequest" do
      optional :name, :string, 1
      optional :func_args, :message, 2, "hashicorp.vagrant.sdk.FuncSpec.Args"
    end
    add_message "hashicorp.vagrant.sdk.Guest.Capability.CheckResp" do
      optional :has_capability, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Guest.Capability.Resp" do
      optional :result, :message, 1, "google.protobuf.Any"
    end
    add_message "hashicorp.vagrant.sdk.Host" do
    end
    add_message "hashicorp.vagrant.sdk.Host.DetectResp" do
      optional :detected, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Host.Capability" do
    end
    add_message "hashicorp.vagrant.sdk.Host.Capability.CheckResp" do
      optional :has_capability, :bool, 1
    end
    add_message "hashicorp.vagrant.sdk.Host.Capability.Resp" do
      optional :result, :message, 1, "google.protobuf.Any"
    end
    add_message "hashicorp.vagrant.sdk.Ref" do
    end
    add_message "hashicorp.vagrant.sdk.Ref.Box" do
      optional :resource_id, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Ref.Project" do
      optional :project_id, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Ref.Machine" do
      optional :resource_id, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine" do
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetNameRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
      optional :name, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetNameResponse" do
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetNameRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetNameResponse" do
      optional :name, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetIDRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
      optional :id, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetIDResponse" do
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetIDRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetIDResponse" do
      optional :id, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetStateRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
      optional :state, :message, 2, "hashicorp.vagrant.sdk.Args.MachineState"
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetStateResponse" do
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetStateRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetStateResponse" do
      optional :state, :message, 1, "hashicorp.vagrant.sdk.Args.MachineState"
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetUUIDRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.GetUUIDResponse" do
      optional :uuid, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetUUIDRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
      optional :uuid, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Machine.SetUUIDResponse" do
    end
    add_message "hashicorp.vagrant.sdk.Machine.BoxRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.BoxResponse" do
      optional :box, :message, 1, "hashicorp.vagrant.sdk.Args.Box"
    end
    add_message "hashicorp.vagrant.sdk.Machine.DatadirRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.DatadirResponse" do
      optional :datadir, :message, 1, "hashicorp.vagrant.sdk.Args.DataDir.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.LocalDataPathRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.LocalDataPathResponse" do
      optional :path, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine.ProviderRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.ProviderResponse" do
      optional :provider, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine.VagrantfileNameRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.VagrantfileNameResponse" do
      optional :name, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine.VagrantfilePathRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.VagrantfilePathResponse" do
      optional :path, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Machine.UpdatedAtRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.UpdatedAtResponse" do
      optional :updated_at, :message, 1, "google.protobuf.Timestamp"
    end
    add_message "hashicorp.vagrant.sdk.Machine.UIRequest" do
      optional :machine, :message, 1, "hashicorp.vagrant.sdk.Ref.Machine"
    end
    add_message "hashicorp.vagrant.sdk.Machine.UIResponse" do
      optional :ui, :message, 1, "hashicorp.vagrant.sdk.Args.TerminalUI"
    end
    add_message "hashicorp.vagrant.sdk.Project" do
    end
    add_message "hashicorp.vagrant.sdk.Project.MachineAndProvider" do
      optional :name, :string, 1
      optional :provider, :string, 2
    end
    add_message "hashicorp.vagrant.sdk.Project.MachineNamesResponse" do
      repeated :names, :string, 1
    end
    add_message "hashicorp.vagrant.sdk.Project.ActiveMachinesRequest" do
      optional :env, :message, 1, "hashicorp.vagrant.sdk.Ref.Project"
    end
    add_message "hashicorp.vagrant.sdk.Project.ActiveMachinesResponse" do
      repeated :machines, :message, 1, "hashicorp.vagrant.sdk.Project.MachineAndProvider"
    end
  end
end

module Hashicorp
  module Vagrant
    module Sdk
      Args = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args").msgclass
      Args::DataDir = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.DataDir").msgclass
      Args::DataDir::Basis = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.DataDir.Basis").msgclass
      Args::DataDir::Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.DataDir.Project").msgclass
      Args::DataDir::Machine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.DataDir.Machine").msgclass
      Args::DataDir::Component = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.DataDir.Component").msgclass
      Args::MachineIndex = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.MachineIndex").msgclass
      Args::MachineIndex::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.MachineIndex.Entry").msgclass
      Args::BoxCollection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.BoxCollection").msgclass
      Args::Box = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Box").msgclass
      Args::Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Project").msgclass
      Args::Machine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Machine").msgclass
      Args::Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Configuration").msgclass
      Args::Configuration::Vagrant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Configuration.Vagrant").msgclass
      Args::Configuration::VM = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Configuration.VM").msgclass
      Args::Configuration::Provider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Configuration.Provider").msgclass
      Args::LabelSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.LabelSet").msgclass
      Args::Options = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Options").msgclass
      Args::Vagrantfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Vagrantfile").msgclass
      Args::JobInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.JobInfo").msgclass
      Args::Logger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.Logger").msgclass
      Args::TerminalUI = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.TerminalUI").msgclass
      Args::StateBag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.StateBag").msgclass
      Args::StateBag::Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.StateBag.Value").msgclass
      Args::MachineState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.MachineState").msgclass
      Args::SSHInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.SSHInfo").msgclass
      Args::WinrmInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.WinrmInfo").msgclass
      Args::WinrmInfo::Transport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Args.WinrmInfo.Transport").enummodule
      FuncSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.FuncSpec").msgclass
      FuncSpec::Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.FuncSpec.Value").msgclass
      FuncSpec::Args = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.FuncSpec.Args").msgclass
      Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Config").msgclass
      Config::ConfigureRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Config.ConfigureRequest").msgclass
      Config::StructResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Config.StructResp").msgclass
      Config::FieldDocumentation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Config.FieldDocumentation").msgclass
      Config::MapperDocumentation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Config.MapperDocumentation").msgclass
      Config::Documentation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Config.Documentation").msgclass
      Auth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Auth").msgclass
      Auth::AuthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Auth.AuthResponse").msgclass
      ImplementsResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.ImplementsResp").msgclass
      TerminalUI = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI").msgclass
      TerminalUI::IsInteractiveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.IsInteractiveResponse").msgclass
      TerminalUI::OutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.OutputRequest").msgclass
      TerminalUI::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Response").msgclass
      TerminalUI::Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event").msgclass
      TerminalUI::Event::Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.Input").msgclass
      TerminalUI::Event::InputResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.InputResp").msgclass
      TerminalUI::Event::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.Status").msgclass
      TerminalUI::Event::Line = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.Line").msgclass
      TerminalUI::Event::Raw = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.Raw").msgclass
      TerminalUI::Event::NamedValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.NamedValue").msgclass
      TerminalUI::Event::NamedValues = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.NamedValues").msgclass
      TerminalUI::Event::TableEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.TableEntry").msgclass
      TerminalUI::Event::TableRow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.TableRow").msgclass
      TerminalUI::Event::Table = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.Table").msgclass
      TerminalUI::Event::StepGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.StepGroup").msgclass
      TerminalUI::Event::Step = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.TerminalUI.Event.Step").msgclass
      Map = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Map").msgclass
      Map::Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Map.Request").msgclass
      Map::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Map.Response").msgclass
      Map::ListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Map.ListResponse").msgclass
      Provider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Provider").msgclass
      Provider::UsableResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Provider.UsableResp").msgclass
      Provider::InstalledResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Provider.InstalledResp").msgclass
      Provider::ActionResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Provider.ActionResp").msgclass
      Command = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command").msgclass
      Command::Flag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.Flag").msgclass
      Command::Flag::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.Flag.Type").enummodule
      Command::CommandInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.CommandInfo").msgclass
      Command::CommandInfoResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.CommandInfoResp").msgclass
      Command::ExecuteResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.ExecuteResp").msgclass
      Command::ExecuteReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.ExecuteReq").msgclass
      Command::ExecuteSpecReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.ExecuteSpecReq").msgclass
      Command::Arguments = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.Arguments").msgclass
      Command::Arguments::Flag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.Arguments.Flag").msgclass
      Command::Arguments::Flag::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Command.Arguments.Flag.Type").enummodule
      Communicator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator").msgclass
      Communicator::MatchResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.MatchResp").msgclass
      Communicator::InitResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.InitResp").msgclass
      Communicator::ReadyResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.ReadyResp").msgclass
      Communicator::FileTransferResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.FileTransferResp").msgclass
      Communicator::ExecutionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.ExecutionRequest").msgclass
      Communicator::ExecuteResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.ExecuteResp").msgclass
      Communicator::TestResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.TestResp").msgclass
      Communicator::ResetResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Communicator.ResetResp").msgclass
      Guest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Guest").msgclass
      Guest::DetectResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Guest.DetectResp").msgclass
      Guest::Capability = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Guest.Capability").msgclass
      Guest::Capability::NamedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Guest.Capability.NamedRequest").msgclass
      Guest::Capability::CheckResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Guest.Capability.CheckResp").msgclass
      Guest::Capability::Resp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Guest.Capability.Resp").msgclass
      Host = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Host").msgclass
      Host::DetectResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Host.DetectResp").msgclass
      Host::Capability = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Host.Capability").msgclass
      Host::Capability::CheckResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Host.Capability.CheckResp").msgclass
      Host::Capability::Resp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Host.Capability.Resp").msgclass
      Ref = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Ref").msgclass
      Ref::Box = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Ref.Box").msgclass
      Ref::Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Ref.Project").msgclass
      Ref::Machine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Ref.Machine").msgclass
      Machine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine").msgclass
      Machine::SetNameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetNameRequest").msgclass
      Machine::SetNameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetNameResponse").msgclass
      Machine::GetNameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetNameRequest").msgclass
      Machine::GetNameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetNameResponse").msgclass
      Machine::SetIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetIDRequest").msgclass
      Machine::SetIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetIDResponse").msgclass
      Machine::GetIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetIDRequest").msgclass
      Machine::GetIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetIDResponse").msgclass
      Machine::SetStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetStateRequest").msgclass
      Machine::SetStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetStateResponse").msgclass
      Machine::GetStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetStateRequest").msgclass
      Machine::GetStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetStateResponse").msgclass
      Machine::GetUUIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetUUIDRequest").msgclass
      Machine::GetUUIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.GetUUIDResponse").msgclass
      Machine::SetUUIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetUUIDRequest").msgclass
      Machine::SetUUIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.SetUUIDResponse").msgclass
      Machine::BoxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.BoxRequest").msgclass
      Machine::BoxResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.BoxResponse").msgclass
      Machine::DatadirRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.DatadirRequest").msgclass
      Machine::DatadirResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.DatadirResponse").msgclass
      Machine::LocalDataPathRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.LocalDataPathRequest").msgclass
      Machine::LocalDataPathResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.LocalDataPathResponse").msgclass
      Machine::ProviderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.ProviderRequest").msgclass
      Machine::ProviderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.ProviderResponse").msgclass
      Machine::VagrantfileNameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.VagrantfileNameRequest").msgclass
      Machine::VagrantfileNameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.VagrantfileNameResponse").msgclass
      Machine::VagrantfilePathRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.VagrantfilePathRequest").msgclass
      Machine::VagrantfilePathResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.VagrantfilePathResponse").msgclass
      Machine::UpdatedAtRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.UpdatedAtRequest").msgclass
      Machine::UpdatedAtResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.UpdatedAtResponse").msgclass
      Machine::UIRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.UIRequest").msgclass
      Machine::UIResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Machine.UIResponse").msgclass
      Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Project").msgclass
      Project::MachineAndProvider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Project.MachineAndProvider").msgclass
      Project::MachineNamesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Project.MachineNamesResponse").msgclass
      Project::ActiveMachinesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Project.ActiveMachinesRequest").msgclass
      Project::ActiveMachinesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.sdk.Project.ActiveMachinesResponse").msgclass
    end
  end
end
