// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vagrant_caps/capabilities.proto

package vagrant_caps

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import vagrant_common "github.com/hashicorp/vagrant/ext/go-plugin/vagrant/plugin/proto/vagrant_common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Capability struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Capability) Reset()         { *m = Capability{} }
func (m *Capability) String() string { return proto.CompactTextString(m) }
func (*Capability) ProtoMessage()    {}
func (*Capability) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{0}
}
func (m *Capability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capability.Unmarshal(m, b)
}
func (m *Capability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capability.Marshal(b, m, deterministic)
}
func (m *Capability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capability.Merge(m, src)
}
func (m *Capability) XXX_Size() int {
	return xxx_messageInfo_Capability.Size(m)
}
func (m *Capability) XXX_DiscardUnknown() {
	xxx_messageInfo_Capability.DiscardUnknown(m)
}

var xxx_messageInfo_Capability proto.InternalMessageInfo

func (m *Capability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Capability) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type ProviderCapability struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderCapability) Reset()         { *m = ProviderCapability{} }
func (m *ProviderCapability) String() string { return proto.CompactTextString(m) }
func (*ProviderCapability) ProtoMessage()    {}
func (*ProviderCapability) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{1}
}
func (m *ProviderCapability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderCapability.Unmarshal(m, b)
}
func (m *ProviderCapability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderCapability.Marshal(b, m, deterministic)
}
func (m *ProviderCapability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderCapability.Merge(m, src)
}
func (m *ProviderCapability) XXX_Size() int {
	return xxx_messageInfo_ProviderCapability.Size(m)
}
func (m *ProviderCapability) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderCapability.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderCapability proto.InternalMessageInfo

func (m *ProviderCapability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProviderCapability) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type ProviderCapabilitiesResponse struct {
	Capabilities         []*ProviderCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Error                string                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProviderCapabilitiesResponse) Reset()         { *m = ProviderCapabilitiesResponse{} }
func (m *ProviderCapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*ProviderCapabilitiesResponse) ProtoMessage()    {}
func (*ProviderCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{2}
}
func (m *ProviderCapabilitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderCapabilitiesResponse.Unmarshal(m, b)
}
func (m *ProviderCapabilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderCapabilitiesResponse.Marshal(b, m, deterministic)
}
func (m *ProviderCapabilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderCapabilitiesResponse.Merge(m, src)
}
func (m *ProviderCapabilitiesResponse) XXX_Size() int {
	return xxx_messageInfo_ProviderCapabilitiesResponse.Size(m)
}
func (m *ProviderCapabilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderCapabilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderCapabilitiesResponse proto.InternalMessageInfo

func (m *ProviderCapabilitiesResponse) GetCapabilities() []*ProviderCapability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *ProviderCapabilitiesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ProviderCapabilityRequest struct {
	Capability           *ProviderCapability `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Machine              string              `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	Arguments            string              `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProviderCapabilityRequest) Reset()         { *m = ProviderCapabilityRequest{} }
func (m *ProviderCapabilityRequest) String() string { return proto.CompactTextString(m) }
func (*ProviderCapabilityRequest) ProtoMessage()    {}
func (*ProviderCapabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{3}
}
func (m *ProviderCapabilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderCapabilityRequest.Unmarshal(m, b)
}
func (m *ProviderCapabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderCapabilityRequest.Marshal(b, m, deterministic)
}
func (m *ProviderCapabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderCapabilityRequest.Merge(m, src)
}
func (m *ProviderCapabilityRequest) XXX_Size() int {
	return xxx_messageInfo_ProviderCapabilityRequest.Size(m)
}
func (m *ProviderCapabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderCapabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderCapabilityRequest proto.InternalMessageInfo

func (m *ProviderCapabilityRequest) GetCapability() *ProviderCapability {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *ProviderCapabilityRequest) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

func (m *ProviderCapabilityRequest) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

type ProviderCapabilityResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderCapabilityResponse) Reset()         { *m = ProviderCapabilityResponse{} }
func (m *ProviderCapabilityResponse) String() string { return proto.CompactTextString(m) }
func (*ProviderCapabilityResponse) ProtoMessage()    {}
func (*ProviderCapabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{4}
}
func (m *ProviderCapabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderCapabilityResponse.Unmarshal(m, b)
}
func (m *ProviderCapabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderCapabilityResponse.Marshal(b, m, deterministic)
}
func (m *ProviderCapabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderCapabilityResponse.Merge(m, src)
}
func (m *ProviderCapabilityResponse) XXX_Size() int {
	return xxx_messageInfo_ProviderCapabilityResponse.Size(m)
}
func (m *ProviderCapabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderCapabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderCapabilityResponse proto.InternalMessageInfo

func (m *ProviderCapabilityResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ProviderCapabilityResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CapabilitiesResponse struct {
	Capabilities         []*Capability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CapabilitiesResponse) Reset()         { *m = CapabilitiesResponse{} }
func (m *CapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*CapabilitiesResponse) ProtoMessage()    {}
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{5}
}
func (m *CapabilitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapabilitiesResponse.Unmarshal(m, b)
}
func (m *CapabilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapabilitiesResponse.Marshal(b, m, deterministic)
}
func (m *CapabilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapabilitiesResponse.Merge(m, src)
}
func (m *CapabilitiesResponse) XXX_Size() int {
	return xxx_messageInfo_CapabilitiesResponse.Size(m)
}
func (m *CapabilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CapabilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CapabilitiesResponse proto.InternalMessageInfo

func (m *CapabilitiesResponse) GetCapabilities() []*Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *CapabilitiesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GuestCapabilityRequest struct {
	Capability           *Capability `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Machine              string      `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	Arguments            string      `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GuestCapabilityRequest) Reset()         { *m = GuestCapabilityRequest{} }
func (m *GuestCapabilityRequest) String() string { return proto.CompactTextString(m) }
func (*GuestCapabilityRequest) ProtoMessage()    {}
func (*GuestCapabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{6}
}
func (m *GuestCapabilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestCapabilityRequest.Unmarshal(m, b)
}
func (m *GuestCapabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestCapabilityRequest.Marshal(b, m, deterministic)
}
func (m *GuestCapabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestCapabilityRequest.Merge(m, src)
}
func (m *GuestCapabilityRequest) XXX_Size() int {
	return xxx_messageInfo_GuestCapabilityRequest.Size(m)
}
func (m *GuestCapabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestCapabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GuestCapabilityRequest proto.InternalMessageInfo

func (m *GuestCapabilityRequest) GetCapability() *Capability {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *GuestCapabilityRequest) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

func (m *GuestCapabilityRequest) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

type GuestCapabilityResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestCapabilityResponse) Reset()         { *m = GuestCapabilityResponse{} }
func (m *GuestCapabilityResponse) String() string { return proto.CompactTextString(m) }
func (*GuestCapabilityResponse) ProtoMessage()    {}
func (*GuestCapabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{7}
}
func (m *GuestCapabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestCapabilityResponse.Unmarshal(m, b)
}
func (m *GuestCapabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestCapabilityResponse.Marshal(b, m, deterministic)
}
func (m *GuestCapabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestCapabilityResponse.Merge(m, src)
}
func (m *GuestCapabilityResponse) XXX_Size() int {
	return xxx_messageInfo_GuestCapabilityResponse.Size(m)
}
func (m *GuestCapabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestCapabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GuestCapabilityResponse proto.InternalMessageInfo

func (m *GuestCapabilityResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *GuestCapabilityResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type HostCapabilityRequest struct {
	Capability           *Capability `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Environment          string      `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Arguments            string      `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HostCapabilityRequest) Reset()         { *m = HostCapabilityRequest{} }
func (m *HostCapabilityRequest) String() string { return proto.CompactTextString(m) }
func (*HostCapabilityRequest) ProtoMessage()    {}
func (*HostCapabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{8}
}
func (m *HostCapabilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostCapabilityRequest.Unmarshal(m, b)
}
func (m *HostCapabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostCapabilityRequest.Marshal(b, m, deterministic)
}
func (m *HostCapabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostCapabilityRequest.Merge(m, src)
}
func (m *HostCapabilityRequest) XXX_Size() int {
	return xxx_messageInfo_HostCapabilityRequest.Size(m)
}
func (m *HostCapabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostCapabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostCapabilityRequest proto.InternalMessageInfo

func (m *HostCapabilityRequest) GetCapability() *Capability {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *HostCapabilityRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *HostCapabilityRequest) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

type HostCapabilityResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostCapabilityResponse) Reset()         { *m = HostCapabilityResponse{} }
func (m *HostCapabilityResponse) String() string { return proto.CompactTextString(m) }
func (*HostCapabilityResponse) ProtoMessage()    {}
func (*HostCapabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_591a3013bd09a9cb, []int{9}
}
func (m *HostCapabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostCapabilityResponse.Unmarshal(m, b)
}
func (m *HostCapabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostCapabilityResponse.Marshal(b, m, deterministic)
}
func (m *HostCapabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostCapabilityResponse.Merge(m, src)
}
func (m *HostCapabilityResponse) XXX_Size() int {
	return xxx_messageInfo_HostCapabilityResponse.Size(m)
}
func (m *HostCapabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostCapabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostCapabilityResponse proto.InternalMessageInfo

func (m *HostCapabilityResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *HostCapabilityResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Capability)(nil), "vagrant.caps.Capability")
	proto.RegisterType((*ProviderCapability)(nil), "vagrant.caps.ProviderCapability")
	proto.RegisterType((*ProviderCapabilitiesResponse)(nil), "vagrant.caps.ProviderCapabilitiesResponse")
	proto.RegisterType((*ProviderCapabilityRequest)(nil), "vagrant.caps.ProviderCapabilityRequest")
	proto.RegisterType((*ProviderCapabilityResponse)(nil), "vagrant.caps.ProviderCapabilityResponse")
	proto.RegisterType((*CapabilitiesResponse)(nil), "vagrant.caps.CapabilitiesResponse")
	proto.RegisterType((*GuestCapabilityRequest)(nil), "vagrant.caps.GuestCapabilityRequest")
	proto.RegisterType((*GuestCapabilityResponse)(nil), "vagrant.caps.GuestCapabilityResponse")
	proto.RegisterType((*HostCapabilityRequest)(nil), "vagrant.caps.HostCapabilityRequest")
	proto.RegisterType((*HostCapabilityResponse)(nil), "vagrant.caps.HostCapabilityResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GuestCapabilitiesClient is the client API for GuestCapabilities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuestCapabilitiesClient interface {
	GuestCapabilities(ctx context.Context, in *vagrant_common.NullRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	GuestCapability(ctx context.Context, in *GuestCapabilityRequest, opts ...grpc.CallOption) (*GuestCapabilityResponse, error)
}

type guestCapabilitiesClient struct {
	cc *grpc.ClientConn
}

func NewGuestCapabilitiesClient(cc *grpc.ClientConn) GuestCapabilitiesClient {
	return &guestCapabilitiesClient{cc}
}

func (c *guestCapabilitiesClient) GuestCapabilities(ctx context.Context, in *vagrant_common.NullRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/vagrant.caps.GuestCapabilities/GuestCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestCapabilitiesClient) GuestCapability(ctx context.Context, in *GuestCapabilityRequest, opts ...grpc.CallOption) (*GuestCapabilityResponse, error) {
	out := new(GuestCapabilityResponse)
	err := c.cc.Invoke(ctx, "/vagrant.caps.GuestCapabilities/GuestCapability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestCapabilitiesServer is the server API for GuestCapabilities service.
type GuestCapabilitiesServer interface {
	GuestCapabilities(context.Context, *vagrant_common.NullRequest) (*CapabilitiesResponse, error)
	GuestCapability(context.Context, *GuestCapabilityRequest) (*GuestCapabilityResponse, error)
}

func RegisterGuestCapabilitiesServer(s *grpc.Server, srv GuestCapabilitiesServer) {
	s.RegisterService(&_GuestCapabilities_serviceDesc, srv)
}

func _GuestCapabilities_GuestCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vagrant_common.NullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestCapabilitiesServer).GuestCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vagrant.caps.GuestCapabilities/GuestCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestCapabilitiesServer).GuestCapabilities(ctx, req.(*vagrant_common.NullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestCapabilities_GuestCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestCapabilitiesServer).GuestCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vagrant.caps.GuestCapabilities/GuestCapability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestCapabilitiesServer).GuestCapability(ctx, req.(*GuestCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuestCapabilities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vagrant.caps.GuestCapabilities",
	HandlerType: (*GuestCapabilitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GuestCapabilities",
			Handler:    _GuestCapabilities_GuestCapabilities_Handler,
		},
		{
			MethodName: "GuestCapability",
			Handler:    _GuestCapabilities_GuestCapability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vagrant_caps/capabilities.proto",
}

// HostCapabilitiesClient is the client API for HostCapabilities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HostCapabilitiesClient interface {
	HostCapabilities(ctx context.Context, in *vagrant_common.NullRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	HostCapability(ctx context.Context, in *HostCapabilityRequest, opts ...grpc.CallOption) (*HostCapabilityResponse, error)
}

type hostCapabilitiesClient struct {
	cc *grpc.ClientConn
}

func NewHostCapabilitiesClient(cc *grpc.ClientConn) HostCapabilitiesClient {
	return &hostCapabilitiesClient{cc}
}

func (c *hostCapabilitiesClient) HostCapabilities(ctx context.Context, in *vagrant_common.NullRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/vagrant.caps.HostCapabilities/HostCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostCapabilitiesClient) HostCapability(ctx context.Context, in *HostCapabilityRequest, opts ...grpc.CallOption) (*HostCapabilityResponse, error) {
	out := new(HostCapabilityResponse)
	err := c.cc.Invoke(ctx, "/vagrant.caps.HostCapabilities/HostCapability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostCapabilitiesServer is the server API for HostCapabilities service.
type HostCapabilitiesServer interface {
	HostCapabilities(context.Context, *vagrant_common.NullRequest) (*CapabilitiesResponse, error)
	HostCapability(context.Context, *HostCapabilityRequest) (*HostCapabilityResponse, error)
}

func RegisterHostCapabilitiesServer(s *grpc.Server, srv HostCapabilitiesServer) {
	s.RegisterService(&_HostCapabilities_serviceDesc, srv)
}

func _HostCapabilities_HostCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vagrant_common.NullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostCapabilitiesServer).HostCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vagrant.caps.HostCapabilities/HostCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostCapabilitiesServer).HostCapabilities(ctx, req.(*vagrant_common.NullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostCapabilities_HostCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostCapabilitiesServer).HostCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vagrant.caps.HostCapabilities/HostCapability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostCapabilitiesServer).HostCapability(ctx, req.(*HostCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HostCapabilities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vagrant.caps.HostCapabilities",
	HandlerType: (*HostCapabilitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostCapabilities",
			Handler:    _HostCapabilities_HostCapabilities_Handler,
		},
		{
			MethodName: "HostCapability",
			Handler:    _HostCapabilities_HostCapability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vagrant_caps/capabilities.proto",
}

// ProviderCapabilitiesClient is the client API for ProviderCapabilities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderCapabilitiesClient interface {
	ProviderCapabilities(ctx context.Context, in *vagrant_common.NullRequest, opts ...grpc.CallOption) (*ProviderCapabilitiesResponse, error)
	ProviderCapability(ctx context.Context, in *ProviderCapabilityRequest, opts ...grpc.CallOption) (*ProviderCapabilityResponse, error)
}

type providerCapabilitiesClient struct {
	cc *grpc.ClientConn
}

func NewProviderCapabilitiesClient(cc *grpc.ClientConn) ProviderCapabilitiesClient {
	return &providerCapabilitiesClient{cc}
}

func (c *providerCapabilitiesClient) ProviderCapabilities(ctx context.Context, in *vagrant_common.NullRequest, opts ...grpc.CallOption) (*ProviderCapabilitiesResponse, error) {
	out := new(ProviderCapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/vagrant.caps.ProviderCapabilities/ProviderCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerCapabilitiesClient) ProviderCapability(ctx context.Context, in *ProviderCapabilityRequest, opts ...grpc.CallOption) (*ProviderCapabilityResponse, error) {
	out := new(ProviderCapabilityResponse)
	err := c.cc.Invoke(ctx, "/vagrant.caps.ProviderCapabilities/ProviderCapability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderCapabilitiesServer is the server API for ProviderCapabilities service.
type ProviderCapabilitiesServer interface {
	ProviderCapabilities(context.Context, *vagrant_common.NullRequest) (*ProviderCapabilitiesResponse, error)
	ProviderCapability(context.Context, *ProviderCapabilityRequest) (*ProviderCapabilityResponse, error)
}

func RegisterProviderCapabilitiesServer(s *grpc.Server, srv ProviderCapabilitiesServer) {
	s.RegisterService(&_ProviderCapabilities_serviceDesc, srv)
}

func _ProviderCapabilities_ProviderCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vagrant_common.NullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderCapabilitiesServer).ProviderCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vagrant.caps.ProviderCapabilities/ProviderCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderCapabilitiesServer).ProviderCapabilities(ctx, req.(*vagrant_common.NullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderCapabilities_ProviderCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderCapabilitiesServer).ProviderCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vagrant.caps.ProviderCapabilities/ProviderCapability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderCapabilitiesServer).ProviderCapability(ctx, req.(*ProviderCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProviderCapabilities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vagrant.caps.ProviderCapabilities",
	HandlerType: (*ProviderCapabilitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProviderCapabilities",
			Handler:    _ProviderCapabilities_ProviderCapabilities_Handler,
		},
		{
			MethodName: "ProviderCapability",
			Handler:    _ProviderCapabilities_ProviderCapability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vagrant_caps/capabilities.proto",
}

func init() { proto.RegisterFile("vagrant_caps/capabilities.proto", fileDescriptor_591a3013bd09a9cb) }

var fileDescriptor_591a3013bd09a9cb = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb5, 0x14, 0x0a, 0x9d, 0x56, 0xfc, 0x59, 0x85, 0x60, 0x4c, 0x25, 0x22, 0x53, 0x44,
	0x84, 0x84, 0x2d, 0x85, 0x0b, 0x87, 0x1e, 0x90, 0xa8, 0x28, 0xe2, 0x80, 0x50, 0xe0, 0x56, 0x89,
	0x6a, 0x63, 0x16, 0x7b, 0x91, 0xbd, 0x6b, 0x76, 0xd7, 0x11, 0xe5, 0x11, 0xb8, 0x71, 0xe0, 0x8d,
	0xb8, 0xf0, 0x16, 0x3c, 0x0a, 0xb2, 0xbd, 0x71, 0xed, 0x7a, 0x5d, 0x97, 0xd2, 0x53, 0x32, 0x93,
	0x99, 0xf9, 0xe6, 0xfb, 0xd9, 0x9a, 0xc0, 0xfd, 0x25, 0x89, 0x24, 0xe1, 0xfa, 0x30, 0x24, 0x99,
	0x0a, 0x42, 0x92, 0x91, 0x05, 0x4b, 0x98, 0x66, 0x54, 0xf9, 0x99, 0x14, 0x5a, 0xe0, 0x2d, 0x53,
	0xe0, 0x17, 0x05, 0xee, 0x41, 0xc4, 0x74, 0x9c, 0x2f, 0xfc, 0x50, 0xa4, 0x41, 0x4c, 0x54, 0xcc,
	0x42, 0x21, 0xb3, 0xc0, 0x94, 0x04, 0xf4, 0xab, 0x0e, 0x22, 0xf1, 0x24, 0x4b, 0xf2, 0x88, 0xf1,
	0x3a, 0x6b, 0xc2, 0x72, 0x5c, 0x50, 0xcb, 0x89, 0x34, 0x15, 0x3c, 0xa8, 0x3e, 0x2a, 0x29, 0x6f,
	0x17, 0xe0, 0xc5, 0x6a, 0x81, 0x23, 0x8c, 0xe1, 0x32, 0x27, 0x29, 0x75, 0xd0, 0x04, 0x4d, 0x37,
	0xe6, 0xe5, 0x77, 0xec, 0xc2, 0xb5, 0x2c, 0x21, 0xfa, 0x93, 0x90, 0xa9, 0x73, 0xa9, 0xcc, 0xd7,
	0xb1, 0xb7, 0x07, 0xf8, 0xad, 0x14, 0x4b, 0xf6, 0x91, 0xca, 0x33, 0x4c, 0x31, 0x95, 0xf5, 0x14,
	0x13, 0x7b, 0xdf, 0x60, 0xbb, 0x33, 0x85, 0x51, 0x35, 0xa7, 0x2a, 0x13, 0x5c, 0x51, 0xbc, 0x07,
	0x5b, 0x4d, 0x48, 0x0e, 0x9a, 0xac, 0x4d, 0x37, 0x67, 0x13, 0xbf, 0x49, 0xc9, 0xef, 0xee, 0x31,
	0x6f, 0x75, 0xe1, 0x11, 0x5c, 0xa1, 0x52, 0x8a, 0x95, 0x7c, 0x15, 0x78, 0x3f, 0x11, 0xdc, 0xb5,
	0xb4, 0xd2, 0x2f, 0x39, 0x55, 0x1a, 0x3f, 0x07, 0xa8, 0x67, 0x1c, 0x95, 0x7e, 0xce, 0xa2, 0xdb,
	0xe8, 0xc1, 0x0e, 0x5c, 0x4d, 0x49, 0x18, 0x33, 0x4e, 0x8d, 0xee, 0x2a, 0xc4, 0xdb, 0xb0, 0x41,
	0x64, 0x94, 0xa7, 0x94, 0x6b, 0xe5, 0xac, 0x95, 0xbf, 0x1d, 0x27, 0xbc, 0xd7, 0xe0, 0xda, 0xd6,
	0x32, 0x44, 0xc6, 0xb0, 0x2e, 0xa9, 0xca, 0x13, 0x6d, 0x18, 0x9b, 0xa8, 0xc7, 0xe3, 0x67, 0x18,
	0x59, 0xb9, 0xee, 0x5a, 0xb9, 0x3a, 0x6d, 0x7f, 0xff, 0xc8, 0xf3, 0x3b, 0x82, 0xf1, 0x7e, 0xc1,
	0xae, 0x0b, 0xf3, 0x99, 0x05, 0x66, 0xbf, 0xd8, 0x45, 0x40, 0xdc, 0x87, 0x3b, 0x9d, 0x5d, 0xce,
	0x45, 0xf0, 0x07, 0x82, 0xdb, 0xaf, 0xc4, 0xc5, 0x9a, 0x9a, 0xc0, 0x26, 0xe5, 0x4b, 0x26, 0x05,
	0x2f, 0x96, 0x35, 0x7a, 0xcd, 0xd4, 0x80, 0xb9, 0x97, 0x30, 0x3e, 0xb9, 0xd2, 0x79, 0xbc, 0xcd,
	0x7e, 0x23, 0xb8, 0xd5, 0xa6, 0x54, 0x3c, 0xdd, 0xf7, 0xb6, 0xe4, 0xbd, 0x63, 0x63, 0xd5, 0x0d,
	0x79, 0x93, 0x27, 0x89, 0x21, 0xe1, 0x7a, 0x3d, 0xae, 0x9b, 0x6f, 0xdc, 0x07, 0xb8, 0x71, 0xe2,
	0x81, 0xe0, 0x9d, 0x76, 0x9b, 0xfd, 0xdd, 0x71, 0x1f, 0x0e, 0x54, 0x55, 0xf3, 0x67, 0xbf, 0x10,
	0xdc, 0x6c, 0x41, 0x29, 0xb6, 0x7e, 0x67, 0xc9, 0xfd, 0xb7, 0x93, 0x03, 0xb8, 0xde, 0xa6, 0x8f,
	0x1f, 0xb4, 0xbb, 0xac, 0xaf, 0x8b, 0xbb, 0x73, 0x7a, 0x91, 0xb1, 0xf1, 0x07, 0xc1, 0xc8, 0x76,
	0x11, 0xf1, 0x61, 0x4f, 0xfe, 0x54, 0x3b, 0x8f, 0x07, 0x0e, 0x56, 0xd3, 0x56, 0x64, 0x3d, 0xe8,
	0x8f, 0x06, 0x4f, 0x9e, 0x91, 0x9a, 0x0e, 0x17, 0x56, 0x42, 0x8b, 0xf5, 0xf2, 0xef, 0xe7, 0xe9,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xfc, 0x96, 0xa9, 0x0c, 0x07, 0x00, 0x00,
}
