# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vagrant.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vagrant.proto", :syntax => :proto3) do
    add_message "vagrant.proto.Empty" do
    end
    add_message "vagrant.proto.Machine" do
      optional :machine, :string, 1
    end
    add_message "vagrant.proto.Valid" do
      optional :result, :bool, 1
    end
    add_message "vagrant.proto.Identifier" do
      optional :name, :string, 1
    end
    add_message "vagrant.proto.PluginInfo" do
      optional :description, :string, 1
      optional :priority, :int64, 2
    end
    add_message "vagrant.proto.Content" do
      optional :target, :string, 1
      optional :value, :string, 2
    end
    add_message "vagrant.proto.WriteResponse" do
      optional :length, :int32, 1
    end
    add_message "vagrant.proto.SystemCapability" do
      optional :name, :string, 1
      optional :platform, :string, 2
    end
    add_message "vagrant.proto.ProviderCapability" do
      optional :name, :string, 1
      optional :provider, :string, 2
    end
    add_message "vagrant.proto.SystemCapabilityList" do
      repeated :capabilities, :message, 1, "vagrant.proto.SystemCapability"
    end
    add_message "vagrant.proto.ProviderCapabilityList" do
      repeated :capabilities, :message, 1, "vagrant.proto.ProviderCapability"
    end
    add_message "vagrant.proto.GenericResponse" do
      optional :result, :string, 1
    end
    add_message "vagrant.proto.GuestCapabilityRequest" do
      optional :capability, :message, 1, "vagrant.proto.SystemCapability"
      optional :machine, :string, 2
      optional :arguments, :string, 3
    end
    add_message "vagrant.proto.HostCapabilityRequest" do
      optional :capability, :message, 1, "vagrant.proto.SystemCapability"
      optional :environment, :string, 2
      optional :arguments, :string, 3
    end
    add_message "vagrant.proto.ProviderCapabilityRequest" do
      optional :capability, :message, 1, "vagrant.proto.ProviderCapability"
      optional :machine, :string, 2
      optional :arguments, :string, 3
    end
    add_message "vagrant.proto.Configuration" do
      optional :data, :string, 1
      optional :machine, :string, 2
    end
    add_message "vagrant.proto.ListResponse" do
      repeated :items, :string, 1
    end
    add_message "vagrant.proto.SyncedFolders" do
      optional :machine, :string, 1
      optional :folders, :string, 2
      optional :options, :string, 3
    end
    add_message "vagrant.proto.GenericAction" do
      optional :name, :string, 1
      optional :machine, :string, 2
    end
    add_message "vagrant.proto.ExecuteAction" do
      optional :name, :string, 1
      optional :data, :string, 2
      optional :machine, :string, 3
    end
    add_message "vagrant.proto.MachineSshInfo" do
      optional :host, :string, 1
      optional :port, :int64, 2
      optional :private_key_path, :string, 3
      optional :username, :string, 4
    end
    add_message "vagrant.proto.MachineState" do
      optional :id, :string, 1
      optional :short_description, :string, 2
      optional :long_description, :string, 3
    end
  end
end

module Vagrant
  module Proto
    Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.Empty").msgclass
    Machine = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.Machine").msgclass
    Valid = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.Valid").msgclass
    Identifier = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.Identifier").msgclass
    PluginInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.PluginInfo").msgclass
    Content = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.Content").msgclass
    WriteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.WriteResponse").msgclass
    SystemCapability = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.SystemCapability").msgclass
    ProviderCapability = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.ProviderCapability").msgclass
    SystemCapabilityList = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.SystemCapabilityList").msgclass
    ProviderCapabilityList = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.ProviderCapabilityList").msgclass
    GenericResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.GenericResponse").msgclass
    GuestCapabilityRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.GuestCapabilityRequest").msgclass
    HostCapabilityRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.HostCapabilityRequest").msgclass
    ProviderCapabilityRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.ProviderCapabilityRequest").msgclass
    Configuration = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.Configuration").msgclass
    ListResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.ListResponse").msgclass
    SyncedFolders = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.SyncedFolders").msgclass
    GenericAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.GenericAction").msgclass
    ExecuteAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.ExecuteAction").msgclass
    MachineSshInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.MachineSshInfo").msgclass
    MachineState = Google::Protobuf::DescriptorPool.generated_pool.lookup("vagrant.proto.MachineState").msgclass
  end
end
