# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ruby_vagrant/ruby-server.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/ruby_vagrant/ruby-server.proto", :syntax => :proto3) do
    add_message "hashicorp.vagrant.GetPluginsResponse" do
      repeated :plugins, :message, 1, "hashicorp.vagrant.Plugin"
    end
    add_message "hashicorp.vagrant.Plugin" do
      optional :name, :string, 1
      optional :type, :enum, 2, "hashicorp.vagrant.Plugin.Type"
    end
    add_enum "hashicorp.vagrant.Plugin.Type" do
      value :COMMAND, 0
      value :COMMUNICATOR, 1
      value :GUEST, 2
      value :HOST, 3
      value :PROVIDER, 4
      value :PROVISIONER, 5
      value :SYNCED_FOLDER, 6
    end
    add_message "hashicorp.vagrant.ParseVagrantfileRequest" do
      optional :path, :string, 1
    end
    add_message "hashicorp.vagrant.ParseVagrantfileResponse" do
      optional :vagrantfile, :message, 1, "hashicorp.vagrant.VagrantfileComponents.Vagrantfile"
    end
    add_message "hashicorp.vagrant.VagrantfileComponents" do
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.ConfigVM" do
      optional :allow_fstab_modification, :bool, 1
      optional :allow_hosts_modificaion, :bool, 2
      optional :box, :string, 3
      optional :provider, :message, 5, "hashicorp.vagrant.VagrantfileComponents.Provider"
      repeated :networks, :message, 7, "hashicorp.vagrant.VagrantfileComponents.Network"
      repeated :provisioners, :message, 8, "hashicorp.vagrant.VagrantfileComponents.Provisioner"
      repeated :synced_folders, :message, 9, "hashicorp.vagrant.VagrantfileComponents.SyncedFolder"
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.ConfigSSH" do
      optional :compresssion, :bool, 1
      optional :connect_timeout, :int64, 2
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.ConfigWinRM" do
      optional :username, :string, 1
      optional :password, :string, 2
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.ConfigWinssh" do
      optional :forward_agent, :bool, 1
      repeated :forward_env, :string, 2
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.ConfigVagrant" do
      optional :host, :string, 1
      repeated :plugins, :string, 2
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.MachineConfig" do
      optional :name, :string, 1
      optional :config_vm, :message, 2, "hashicorp.vagrant.VagrantfileComponents.ConfigVM"
      optional :config_ssh, :message, 3, "hashicorp.vagrant.VagrantfileComponents.ConfigSSH"
      optional :config_winrm, :message, 4, "hashicorp.vagrant.VagrantfileComponents.ConfigWinRM"
      optional :config_winssh, :message, 5, "hashicorp.vagrant.VagrantfileComponents.ConfigWinssh"
      optional :config_vagrant, :message, 6, "hashicorp.vagrant.VagrantfileComponents.ConfigVagrant"
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.Provisioner" do
      optional :name, :string, 1
      optional :type, :string, 2
      optional :before, :string, 3
      optional :after, :string, 4
      optional :communicator_required, :bool, 5
      optional :config, :message, 6, "google.protobuf.Any"
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.Provider" do
      optional :type, :string, 1
      optional :config, :message, 2, "google.protobuf.Any"
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.Network" do
      optional :type, :string, 1
      oneof :config do
        optional :forwarded_port, :message, 2, "hashicorp.vagrant.VagrantfileComponents.ForwardedPort"
        optional :private_network, :message, 3, "hashicorp.vagrant.VagrantfileComponents.PrivateNetwork"
        optional :public_network, :message, 4, "hashicorp.vagrant.VagrantfileComponents.PublicNetwork"
      end
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.ForwardedPort" do
      optional :auto_correct, :bool, 1
      optional :guest, :int32, 2
      optional :guest_ip, :string, 3
      optional :host, :int32, 4
      optional :host_ip, :string, 5
      optional :id, :string, 6
      optional :protocol, :string, 7
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.PrivateNetwork" do
      optional :type, :string, 1
      optional :auto_config, :bool, 2
      oneof :config do
        optional :dhcp, :message, 3, "hashicorp.vagrant.VagrantfileComponents.DHCP"
        optional :static_ip, :message, 4, "hashicorp.vagrant.VagrantfileComponents.StaticIp"
      end
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.PublicNetwork" do
      optional :type, :string, 1
      optional :auto_config, :bool, 2
      repeated :bridge, :string, 3
      oneof :config do
        optional :dhcp, :message, 4, "hashicorp.vagrant.VagrantfileComponents.DHCP"
        optional :static_ip, :message, 5, "hashicorp.vagrant.VagrantfileComponents.StaticIp"
      end
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.DHCP" do
      optional :use_dhcp_assigned_default_route, :bool, 1
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.StaticIp" do
      optional :ip, :string, 1
      optional :netmask, :string, 2
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.SyncedFolder" do
      optional :source, :string, 1
      optional :destination, :string, 2
      optional :config, :message, 3, "google.protobuf.Any"
      optional :create, :bool, 4
      optional :disabled, :bool, 5
      optional :group, :string, 6
      optional :id, :string, 7
      repeated :mount_options, :string, 8
      optional :owner, :string, 9
      optional :type, :string, 10
    end
    add_message "hashicorp.vagrant.VagrantfileComponents.Vagrantfile" do
      optional :path, :string, 1
      optional :raw, :string, 2
      optional :current_version, :string, 3
      repeated :machine_configs, :message, 4, "hashicorp.vagrant.VagrantfileComponents.MachineConfig"
    end
  end
end

module Hashicorp
  module Vagrant
    GetPluginsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.GetPluginsResponse").msgclass
    Plugin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.Plugin").msgclass
    Plugin::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.Plugin.Type").enummodule
    ParseVagrantfileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.ParseVagrantfileRequest").msgclass
    ParseVagrantfileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.ParseVagrantfileResponse").msgclass
    VagrantfileComponents = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents").msgclass
    VagrantfileComponents::ConfigVM = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.ConfigVM").msgclass
    VagrantfileComponents::ConfigSSH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.ConfigSSH").msgclass
    VagrantfileComponents::ConfigWinRM = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.ConfigWinRM").msgclass
    VagrantfileComponents::ConfigWinssh = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.ConfigWinssh").msgclass
    VagrantfileComponents::ConfigVagrant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.ConfigVagrant").msgclass
    VagrantfileComponents::MachineConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.MachineConfig").msgclass
    VagrantfileComponents::Provisioner = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.Provisioner").msgclass
    VagrantfileComponents::Provider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.Provider").msgclass
    VagrantfileComponents::Network = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.Network").msgclass
    VagrantfileComponents::ForwardedPort = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.ForwardedPort").msgclass
    VagrantfileComponents::PrivateNetwork = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.PrivateNetwork").msgclass
    VagrantfileComponents::PublicNetwork = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.PublicNetwork").msgclass
    VagrantfileComponents::DHCP = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.DHCP").msgclass
    VagrantfileComponents::StaticIp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.StaticIp").msgclass
    VagrantfileComponents::SyncedFolder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.SyncedFolder").msgclass
    VagrantfileComponents::Vagrantfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hashicorp.vagrant.VagrantfileComponents.Vagrantfile").msgclass
  end
end
