// Code generated by "stringer -type=Type -linecomment ./internal/flags"; DO NOT EDIT.

package flags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnsetType-0]
	_ = x[ArrayType-1]
	_ = x[BooleanType-2]
	_ = x[FloatType-3]
	_ = x[IncrementType-4]
	_ = x[IntegerType-5]
	_ = x[MapType-6]
	_ = x[StringType-7]
}

const _Type_name = "UnsetArrayBooleanFloatIncrementIntegerMapString"

var _Type_index = [...]uint8{0, 5, 10, 17, 22, 31, 38, 41, 47}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
