name: Vagrant Ruby Tests
on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'templates/**'
      - 'Gemfile'
      - 'vagrant.gemspec'
      - 'Rakefile'
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'Gemfile'
      - 'templates/**'
      - 'vagrant.gemspec'
      - 'Rakefile'

jobs:
  unit-tests-ruby:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Vagrant unit tests on Ruby ${{ matrix.ruby }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: install dependencies
        run: sudo apt -y install libarchive-tools
      - name: Run Tests
        run: bundle exec rake test:unit
